// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhV10xRnYqrOgMd18nFllYQbFWCeuLA1o',
    appId: '1:890641607442:web:abdcc1e5100970421f61cb',
    messagingSenderId: '890641607442',
    projectId: 'application-mapollege',
    authDomain: 'application-mapollege.firebaseapp.com',
    storageBucket: 'application-mapollege.firebasestorage.app',
    measurementId: 'G-HG1Z0E8ZGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilJ4T4z9RTRmgTGJtvUzFnze9BsrIkr0',
    appId: '1:890641607442:android:6cac390f1e2e87c81f61cb',
    messagingSenderId: '890641607442',
    projectId: 'application-mapollege',
    storageBucket: 'application-mapollege.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4B0yPaM5YFGT8Hm1IYZaH8K4NI79o1xw',
    appId: '1:890641607442:ios:343b42433fd5cd9a1f61cb',
    messagingSenderId: '890641607442',
    projectId: 'application-mapollege',
    storageBucket: 'application-mapollege.firebasestorage.app',
    iosClientId: '890641607442-74fhfeggej670v0gbgootpf9dsko0nsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationMapollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4B0yPaM5YFGT8Hm1IYZaH8K4NI79o1xw',
    appId: '1:890641607442:ios:343b42433fd5cd9a1f61cb',
    messagingSenderId: '890641607442',
    projectId: 'application-mapollege',
    storageBucket: 'application-mapollege.firebasestorage.app',
    iosClientId: '890641607442-74fhfeggej670v0gbgootpf9dsko0nsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationMapollege',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhV10xRnYqrOgMd18nFllYQbFWCeuLA1o',
    appId: '1:890641607442:web:c8d911eefd9126cc1f61cb',
    messagingSenderId: '890641607442',
    projectId: 'application-mapollege',
    authDomain: 'application-mapollege.firebaseapp.com',
    storageBucket: 'application-mapollege.firebasestorage.app',
    measurementId: 'G-S733HJN86B',
  );
}
