import 'package:flutter/material.dart';

class ThemeColor {
  Color get seed => const Color(0xFFFFC107);

  ColorScheme get lightScheme => ColorScheme.fromSeed(
    seedColor: seed,
    brightness: Brightness.light,
    dynamicSchemeVariant: DynamicSchemeVariant.rainbow,
    primary: const Color(0xff785900),
    onPrimary: const Color(0xffffffff),
    primaryContainer: const Color(0xffffc107),
    onPrimaryContainer: const Color(0xff6d5100),
    secondary: const Color(0xff984800),
    onSecondary: const Color(0xffffffff),
    secondaryContainer: const Color(0xfff97a00),
    onSecondaryContainer: const Color(0xff592700),
    error: const Color(0xffba1a1a),
    onError: const Color(0xffffffff),
    errorContainer: const Color(0xffffdad6),
    onErrorContainer: const Color(0xff93000a),
    outline: const Color(0xff827660),
    outlineVariant: const Color(0xffd4c5ab),
    shadow: const Color(0xff000000),
    scrim: const Color(0xff000000),
    inversePrimary: const Color(0xfffabd00),
    primaryFixed: const Color(0xffffdf9e),
    onPrimaryFixed: const Color(0xff261a00),
    primaryFixedDim: const Color(0xfffabd00),
    onPrimaryFixedVariant: const Color(0xff5b4300),
    secondaryFixed: const Color(0xffffdbc8),
    onSecondaryFixed: const Color(0xff311300),
    secondaryFixedDim: const Color(0xffffb689),
    onSecondaryFixedVariant: const Color(0xff733500),
  );

  ColorScheme get darkScheme => ColorScheme.fromSeed(
    seedColor: seed,
    brightness: Brightness.dark,
    dynamicSchemeVariant: DynamicSchemeVariant.rainbow,
    primary: const Color(0xffffe4af),
    onPrimary: const Color(0xff3f2e00),
    primaryContainer: const Color(0xffffc107),
    onPrimaryContainer: const Color(0xff6d5100),
    secondary: const Color(0xffffb689),
    onSecondary: const Color(0xff512300),
    secondaryContainer: const Color(0xfff97a00),
    onSecondaryContainer: const Color(0xff592700),
    error: const Color(0xffffb4ab),
    onError: const Color(0xff690005),
    errorContainer: const Color(0xff93000a),
    onErrorContainer: const Color(0xffffdad6),
    outline: const Color(0xff9c8f78),
    outlineVariant: const Color(0xff4f4632),
    shadow: const Color(0xff000000),
    scrim: const Color(0xff000000),
    inversePrimary: const Color(0xff785900),
    primaryFixed: const Color(0xffffdf9e),
    onPrimaryFixed: const Color(0xff261a00),
    primaryFixedDim: const Color(0xfffabd00),
    onPrimaryFixedVariant: const Color(0xff5b4300),
    secondaryFixed: const Color(0xffffdbc8),
    onSecondaryFixed: const Color(0xff311300),
    secondaryFixedDim: const Color(0xffffb689),
    onSecondaryFixedVariant: const Color(0xff733500),
  );
}
